## 导入数据并且导入图片化模块：PIL(python Image Library)

In [1]:
from sklearn.datasets import load_digits
import numpy as np

from PIL import Image

digits = load_digits()
def img_show(img):
    pil_img = Image.fromarray(img)
    pil_img.show()

## 查看数据集状态 

In [2]:
# print(digits)
# print(digits['data'].shape)
# print(digits['images'].shape)
# print(digits['images'][0])

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'frame': None, 'feature_names': ['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', '

## 尝试图片化，像素太小无法查看

In [3]:
img = digits['data'][0]
print(img.shape)
img = img.reshape(8, 8)
print(img.shape)
print(img)
img_show(img)

(64,)
(8, 8)
[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


## 划分训练集和测试集 

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits['data'], digits['target'], test_size = 0.33, random_state = 3)
# print(x_train)
# print(y_train)
# print(x_test)
# print(y_test)

[[ 0.  1. 10. ...  0.  0.  0.]
 [ 0.  0.  5. ...  4.  0.  0.]
 [ 0.  0.  2. ... 16.  2.  0.]
 ...
 [ 0.  0.  8. ...  4.  0.  0.]
 [ 0.  2. 13. ... 12. 12.  1.]
 [ 0.  0.  6. ...  8.  0.  0.]]
[7 0 9 ... 0 2 1]
[[ 0.  0.  4. ...  2.  0.  0.]
 [ 0.  0.  2. ...  0.  0.  0.]
 [ 0.  0.  0. ... 15.  6.  0.]
 ...
 [ 0.  0.  6. ...  3.  0.  0.]
 [ 0.  0.  0. ... 15.  7.  0.]
 [ 0.  0.  0. ...  8.  0.  0.]]
[0 4 1 2 0 0 8 7 6 6 3 6 9 7 4 7 4 3 2 6 4 3 4 7 1 0 7 4 8 3 4 0 5 5 5 1 2
 9 0 0 0 8 2 3 7 0 1 7 1 3 8 4 2 9 6 0 4 5 4 4 7 9 9 5 0 3 7 4 9 1 8 0 9 3
 0 2 7 8 1 6 9 3 3 2 2 3 8 2 4 6 9 5 8 4 7 3 7 2 5 6 5 6 1 0 6 4 8 1 5 6 8
 8 8 6 4 0 2 7 5 0 8 5 8 4 7 0 5 9 0 1 8 4 7 9 6 1 2 7 1 3 5 3 5 2 7 4 9 2
 0 0 9 2 8 4 0 9 7 0 1 4 1 8 0 7 9 1 9 7 2 7 7 0 5 3 4 0 5 2 3 0 3 0 1 9 5
 4 8 2 6 0 9 7 8 8 7 3 0 9 5 3 6 3 7 9 0 5 7 6 5 3 1 0 4 3 1 0 5 3 7 3 2 3
 5 0 7 4 5 3 0 0 5 7 5 2 4 2 9 3 3 0 9 3 1 3 1 7 4 7 4 5 2 1 1 4 7 1 7 5 2
 5 2 5 0 9 2 0 7 6 5 4 9 1 4 1 8 0 7 4 7 1 3 4 9 5 0 3 0 5 4 3 6 1 4 3 8 

## 使用三种分类器对数据进行分类 

In [5]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score

## 伯努利朴素贝叶斯分类器 

In [14]:
model_b = BernoulliNB()       # 建立模型
model_b = model_b.fit(x_train,y_train)             # 用模型对数据进行拟合
pred_b =model_b.predict(x_test)          # 在测试集上进行预测
accuracy_score_b = accuracy_score(y_test,pred_b)            # 计算准确率
print(f'BermouliNB准确率为：{accuracy_score_b:.4}')

BermouliNB准确率为：0.8333


## 高斯朴素贝叶斯分类器 

In [12]:
model_g = GaussianNB( )
model_g.fit(x_train,y_train)
pred_g = model_g.predict(x_test)
accuracy_score_g = accuracy_score(y_test, pred_g)
print(f'GaussianNB准确率: {accuracy_score_g: .4f}')

GaussianNB准确率:  0.8350


## 多项式朴素贝叶斯分类器 

In [13]:
model_m = MultinomialNB(fit_prior=True)
model_m.fit(x_train,y_train)
pred_m  = model_m.predict(x_test)
accuracy_score_m = accuracy_score(y_test,pred_m)
print(f'MultionmialNB准确率：{accuracy_score_m:.4f}')

MultionmialNB准确率：0.8838
